name: CI/CD with Infisical

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Infisical
      run: |
        curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
        sudo apt-get install infisical -y

    - name: Fetch Secrets
      env:
        INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
      run: |
        infisical export --env=dev --format=dotenv > .env
        sed -i 's/"//g' .env
        cat .env >> $GITHUB_ENV

    - name: Docker Login
      run: |
        echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/war-room-backend ./server
        docker push ${{ env.DOCKER_USERNAME }}/war-room-backend

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USER }}
        key: ${{ env.EC2_SSH_KEY }}
        script: |
          echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
          docker pull ${{ env.DOCKER_USERNAME }}/war-room-backend
          docker stop warroom || true
          docker rm warroom || true
          docker run -d -p 4000:4000 --env-file .env --name warroom ${{ env.DOCKER_USERNAME }}/war-room-backend